version: "3.9"
services:
  seta-mongo:
    container_name: seta-mongo
    restart: always
    build: ./
    expose:
      - "27017"
    networks: 
      - seta-network
    volumes: 
      - seta-mongo:/data/db

networks:
  seta-network:
    name: seta-network
    driver: bridge

volumes:
  seta-mongo:
