services:
  mongo:
    restart: always
    build: 
      context: ../seta-mongo
    expose:
      - "27017"
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}

  es:
    restart: always
    build: 
      context: ../seta-es
    expose:
      - "9200"
      - "9300"
    mem_limit: "4g"
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ingest.geoip.downloader.enabled=false

  api:
    restart: always
    build: 
      context: ../seta-api
    expose:
      - "8081"
    mem_limit: "8g"
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}

  nginx:
    restart: always
    build: 
       context: ../seta-nginx
       dockerfile: Dockerfile
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}

  ui:
    restart: always
    build: 
       context: ../seta-ui
       dockerfile: Dockerfile
    expose:
      - "8080" 
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
      - ROOT_USERS=${ROOT_USERS}
      - API_SECRET_KEY
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET

  ui-react:
    restart: always
    build: 
       context: ../seta-react
       dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}

  data:
    build: 
      context: ../seta-data
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}