version: "3.8"
services:
  seta-mongo:
    container_name: mongo
    extends:
      file: common.yml
      service: mongo
    networks:
      - seta-network
    volumes:
      - seta-mongo:/data/db
      
  seta-es:
    container_name: seta-es
    extends:
      file: common.yml
      service: es
    expose:
      - "9200"
      - "9300"
    volumes:
      - seta-es:/usr/share/elasticsearch/data
    environment:
      - node.name=seta-es
      - cluster.initial_master_nodes=seta-es,seta-es02,seta-es03
      - discovery.seed_hosts=seta-es02,seta-es03
    networks:
      - seta-network

  seta-es02:
    depends_on:
      - seta-es
    extends:
      file: common.yml
      service: es
    container_name: seta-es02
    volumes:
      - seta-es02:/usr/share/elasticsearch/data
    environment:
      - node.name=seta-es02
      - cluster.initial_master_nodes=seta-es,seta-es02,seta-es03
      - discovery.seed_hosts=seta-es,seta-es03
    networks:
      - seta-network

  seta-es03:
    depends_on:
      - seta-es02
    extends:
      file: common.yml
      service: es
    container_name: seta-es03
    volumes:
      - seta-es03:/usr/share/elasticsearch/data
    environment:
      - node.name=seta-es03
      - cluster.initial_master_nodes=seta-es,seta-es02,seta-es03
      - discovery.seed_hosts=seta-es,seta-es02
      - cluster.name=docker-cluster
    networks:
      - seta-network

  seta-api:
    container_name: api
    extends:
      file: common.yml
      service: api
    networks:
      - seta-network
    depends_on:
      - "seta-mongo"
      - "seta-es"

  seta-nginx:
    container_name: nginx
    extends:
      file: common.yml
      service: nginx
    ports:
      - "80:80"
    depends_on:
      - "seta-auth"
      - "seta-api"
      - "seta-ui"
      - "seta-ui-react"
      - "seta-doc"
    networks:
      - seta-network

  seta-ui:
    container_name: ui
    extends:
      file: common.yml
      service: ui
    depends_on:
      - "seta-api"
    networks:
      - seta-network

  seta-ui-react:
    container_name: ui-react
    extends:
      file: common.yml
      service: ui-react
    depends_on:
      - "seta-api"
      - "seta-ui"
    networks: 
      - seta-network

  seta-data:
    container_name: data
    extends:
      file: common.yml
      service: data
    depends_on:
      - "seta-es"
    volumes:
      - seta-models3:/home/seta/models
    networks:
      - seta-network

  seta-doc:
    container_name: doc
    extends:
      file: common.yml
      service: doc
    expose:
      - "80"
    networks:
      - seta-network

  seta-auth:
    container_name: auth
    extends:
      file: common.yml
      service: auth
    depends_on:
      - "seta-mongo"
    networks:
      - seta-network

networks:
  seta-network:
    name: seta-network
    driver: bridge

volumes:
  seta-mongo:
  seta-es:
  seta-es02:
  seta-es03:
  seta-models3: