version: "3.8"
services:
  seta-mongo:
    container_name: mongo
    extends:
      file: common.yml
      service: mongo
    networks:
      - seta-network
    volumes:
      - seta-mongo:/data/db


  seta-opensearch:
    container_name: opensearch
    extends:
      file: common.yml
      service: opensearch
    environment:
      - discovery.type=single-node
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    expose:
      - "9200"
      - "9600"
    networks:
      - seta-network

  seta-api:
    container_name: api
    extends:
      file: common.yml
      service: api
    build:
       dockerfile: seta-api/Dockerfile
    networks:
      - seta-network
    depends_on:
      - "seta-auth"
      - "seta-opensearch"      

  seta-search:
    container_name: search
    extends:
      file: common.yml
      service: search
    build:
      dockerfile: seta-search/Dockerfile
    networks:
      - seta-network
    depends_on:
      - "seta-auth"
      - "seta-opensearch"
      - "seta-nlp"

  seta-nginx:
    container_name: nginx
    extends:
      file: common.yml
      service: nginx
    ports:
      - "80:80"
    depends_on:
      - "seta-auth"
      - "seta-api"
      - "seta-nlp"
      - "seta-search"
      - "seta-ui"
      - "seta-ui-react"
      - "seta-doc"
    networks:
      - seta-network

  seta-ui:
    container_name: ui
    extends:
      file: common.yml
      service: ui
    build:
       dockerfile: seta-ui/dockerfiles/Dockerfile-ui
    depends_on:
      - "seta-auth"
      - "seta-mongo"
      - "seta-admin"
    networks:
      - seta-network

  seta-ui-react:
    container_name: ui-react
    extends:
      file: common.yml
      service: ui-react
    build:
      dockerfile: docker/Dockerfile
    depends_on:
      - "seta-api"
      - "seta-ui"
    networks:
      - seta-network

  seta-data:
    container_name: data
    extends:
      file: common.yml
      service: data
    depends_on:
      - "seta-opensearch"
    volumes:
      - seta-models3:/home/seta/models
    networks:
      - seta-network

  seta-doc:
    container_name: doc
    extends:
      file: common.yml
      service: doc
    expose:
      - "80"
    networks:
      - seta-network

  seta-auth:
    container_name: auth
    extends:
      file: common.yml
      service: auth
    build:
       dockerfile: seta-ui/dockerfiles/Dockerfile-auth
    depends_on:
      - "seta-mongo"
    networks:
      - seta-network

  seta-admin:
    container_name: admin
    extends:
      file: common.yml
      service: admin
    volumes:
      - seta-models3:/home/seta/models
    networks:
      - seta-network
    depends_on:
      - "seta-opensearch"

  seta-nlp:
    container_name: nlp
    extends:
      file: common.yml
      service: nlp
    networks:
      - seta-network

networks:
  seta-network:
    name: seta-network
    driver: bridge

volumes:
  seta-mongo:
  seta-models3:
  opensearch-data:
