version: "3.8"
services:
  seta-mongo:
    container_name: seta-mongo
    restart: always
    build: ../seta-mongo
    expose:
      - "27017"
    networks:
      - seta-network
    volumes:
      - seta-mongo:/data/db
  seta-es:
    container_name: seta-es
    restart: always
    build: ../seta-es
    expose:
      - "9200"
      - "9300"
    mem_limit: "4g"
    volumes:
      - seta-es2:/usr/share/elasticsearch/data
    networks:
      - seta-network
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ingest.geoip.downloader.enabled=false

  seta-api:
    container_name: seta-api
    restart: always
    build: ../seta-api
    expose:
      - "8081"
    mem_limit: "8g"
    volumes:
      - seta-models2:/home/seta/models
    networks:
      - seta-network
    depends_on:
      - "seta-mongo"
      - "seta-es"

  seta-nginx:
    container_name: seta-nginx
    restart: always
    build: 
       context: ../seta-nginx
       dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "seta-api"
      - "seta-ui"
      - "seta-ui-react"
    networks:
      - seta-network

  seta-ui:
    container_name: seta-ui
    restart: always
    build: 
       context: ../seta-ui
       dockerfile: Dockerfile
    depends_on:
      - "seta-api"
    expose:
      - "8080"
    volumes:
      - seta-models2:/home/seta/models
    networks:
      - seta-network


  seta-ui-react:
    container_name: seta-ui-react
    restart: always
    build: 
       context: ../seta-react
       dockerfile: Dockerfile
    depends_on:
      - "seta-api"
      - "seta-ui"
    expose:
      - "3000"
    networks: 
      - seta-network



networks:
  seta-network:
    name: seta-network
    driver: bridge

volumes:
  seta-mongo:
  seta-es2:
  seta-models2:
