version: "3.8"
name: seta-test
services:
  seta-mongo-test:
    container_name: mongo-test
    extends:
      file: common.yml
      service: mongo
    restart: "no"
    ports:
      - "27018:27017"
    networks:
      - seta-network-test      

  seta-es-test:
    container_name: es-test
    restart: "no"   
    build:
      context: ../seta-es
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    mem_limit: "4g"
    environment:
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ingest.geoip.downloader.enabled=false
      - logger.level=WARN
    expose:
      - "9200"
      - "9300"
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    volumes:
      - seta-es3-test:/usr/share/elasticsearch/data
    networks:
      - seta-network-test

  seta-api-test:
    container_name: api-test
    extends:
      file: common.yml
      service: api
    restart: "no"
    build:
      dockerfile: seta-api/Dockerfile-test
    networks:
      - seta-network-test
    depends_on:
      - "seta-mongo-test"
      - "seta-es-test"

  seta-nginx-test:
    container_name: nginx-test
    extends:
      file: common.yml
      service: nginx
    restart: "no"
    build: 
       args:
        - PROJECT_CONF=project_test
    ports:
      - "8080:8080"
    depends_on:
      - "seta-auth-test"
      - "seta-api-test"
      - "seta-ui-test"
    networks:
      - seta-network-test

  seta-ui-test:
    container_name: ui-test
    extends:
      file: common.yml
      service: ui
    restart: "no"
    build: 
      dockerfile: seta-ui/dockerfiles/Dockerfile-ui-test
    depends_on:
      - "seta-api-test"
    networks:
      - seta-network-test

  seta-data-test:
    container_name: data-test
    extends:
      file: common.yml
      service: data
    depends_on:
      - "seta-es-test"
    volumes:
      - seta-models3-test:/home/seta/models
    networks:
      - seta-network-test

  seta-auth-test:
    container_name: auth-test
    extends:
      file: common.yml
      service: auth
    restart: "no"
    build:
      dockerfile: seta-ui/dockerfiles/Dockerfile-auth-test
    networks:
      - seta-network-test
    depends_on:
      - "seta-mongo-test"

networks:
  seta-network-test:
    name: seta-network-test
    driver: bridge

volumes:
  seta-es3-test:
  seta-models3-test: