services:
  seta-mongo:
    ports:
      - "27017:27017"

  seta-es:
    mem_limit: "6g"

  seta-api:
    build:
      dockerfile: Dockerfile-dev-flask
    volumes:
      - ../seta-api:/home/seta
      - /home/seta/tika

  seta-nginx:
    build:
      args:
        - PROJECT_CONF=project_dev

  seta-ui:
    build:
       dockerfile: Dockerfile-dev-flask
    ports:
      - "5678:5678"
    volumes:
      - ../seta-ui:/home/seta

  seta-ui-react:
    build:
       dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ../seta-react:/home/seta
      - /home/seta/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  seta-doc:
    build:       
       dockerfile: Dockerfile-dev
    expose:
      - "8000"
    volumes:
      - ../seta-doc:/home/seta

  seta-auth:
    build:
       dockerfile: Dockerfile-dev
    volumes:
      - ../seta-auth:/home/seta