version: "3.8"
name: seta-prod
services:
  seta-mongo:
    container_name: mongo
    extends:
      file: common.yml
      service: mongo
    networks:
      - seta-network
    volumes:
      - seta-mongo:/data/db
      
  seta-es:
    container_name: es
    extends:      
      file: common.yml
      service: es
    volumes:
      - seta-es3:/usr/share/elasticsearch/data
    networks:
      - seta-network

  seta-api:
    container_name: api
    extends:
      file: common.yml
      service: api
    volumes:
      - seta-models3:/home/seta/models
    networks:
      - seta-network
    depends_on:
      - "seta-mongo"
      - "seta-es"

  seta-nginx:
    container_name: nginx
    extends:
      file: common.yml
      service: nginx
    ports:
      - "80:80"
    depends_on:
      - "seta-api"
      - "seta-ui"
      - "seta-ui-react"
    networks:
      - seta-network

  seta-ui:
    container_name: ui
    extends:
      file: common.yml
      service: ui
    depends_on:
      - "seta-api"
    volumes:
      - seta-models3:/home/seta/models
    networks:
      - seta-network

  seta-ui-react:
    container_name: ui-react
    extends:
      file: common.yml
      service: ui-react
    depends_on:
      - "seta-api"
      - "seta-ui"
    networks: 
      - seta-network

  seta-data:
    container_name: data
    extends:
      file: common.yml
      service: data
    depends_on:
      - "seta-es"
    volumes:
      - seta-models3:/home/seta/models
    networks:
      - seta-network

networks:
  seta-network:
    name: seta-network
    driver: bridge

volumes:
  seta-mongo:
  seta-es3:
  seta-models3: