name: seta-dev
services:
  seta-mongo:
    container_name: mongo-dev
    ports:
      - "27017:27017"

  seta-es:
    container_name: es-dev
    mem_limit: "6g"

  seta-api:
    container_name: api-dev
    build:
      context: ../seta-api
      dockerfile: Dockerfile-dev-flask
    volumes: 
      - ../seta-api:/home/seta
      - seta-models3:/home/seta/models

  seta-nginx:
    container_name: nginx-dev
    build:
      args:
        - PROJECT_CONF=project_dev

  seta-ui:
    container_name: ui-dev
    build: 
       context: ../seta-ui
       dockerfile: Dockerfile-dev-flask
    ports:
      - "5678:5678"
    volumes: 
      - ../seta-ui:/home/seta
      - seta-models3:/home/seta/models

  seta-ui-react:
    container_name: ui-react-dev
    build: 
       context: ../seta-react
       dockerfile: Dockerfile-dev
    volumes: 
      - ../seta-react:/home/seta
      - /home/seta/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  
  seta-data:
    container_name: data-dev