services:
  seta-mongo:
    ports:
      - "27017:27017"

  seta-es:
    mem_limit: "6g"

  seta-api:
    build:
      context: ../seta-api
      dockerfile: Dockerfile-dev-flask
    volumes: 
      - ../seta-api:/home/seta

  seta-nginx:
    build:
      args:
        - PROJECT_CONF=project_dev

  seta-ui:
    build: 
       context: ../seta-ui
       dockerfile: Dockerfile-dev-flask
    ports:
      - "5678:5678"
    volumes: 
      - ../seta-ui:/home/seta

  seta-ui-react:
    build: 
       context: ../seta-react
       dockerfile: Dockerfile-dev
    volumes: 
      - ../seta-react:/home/seta
      - /home/seta/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true