services:
  seta-mongo:
    ports:
      - "27017:27017"

  seta-opensearch:
    mem_limit: "6g"
    environment:
    - logger.level=INFO

  seta-api:
    build:
      dockerfile: seta-api/Dockerfile-dev
    volumes:
      - ../seta-api:/home/seta
      - ../seta-config:/etc/seta
      - /home/seta/tika

  seta-nginx:
    build:
      args:
        - PROJECT_CONF=project_dev

  seta-ui:
    build:
       dockerfile: seta-ui/dockerfiles/Dockerfile-ui-dev
    ports:
      - "5678:5678"
    volumes:
      - ../seta-ui:/home/seta
      - ../seta-config:/etc/seta

  seta-ui-react:
    build:
       dockerfile: docker/Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ../seta-react:/home/seta
      - /home/seta/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  seta-doc:
    build:
       dockerfile: Dockerfile-dev
    expose:
      - "8000"
    volumes:
      - ../seta-doc:/home/seta

  seta-auth:
    build:
       dockerfile: seta-ui/dockerfiles/Dockerfile-auth-dev
    volumes:
      - ../seta-ui:/home/seta
      - ../seta-config:/etc/seta
