services:
  seta-mongo:
    env_file:
      - .env.dev
    ports:
      - "27017:27017"

  seta-es:
    env_file:
      - .env.dev
    mem_limit: "6g"

  seta-api:
    env_file:
      - .env.dev
    build:
      context: ../seta-api
      dockerfile: Dockerfile-dev-flask
    volumes: 
      - ../seta-api:/home/seta
      - seta-models3:/home/seta/models

  seta-nginx:
    env_file:
      - .env.dev
    build:
      args:
        - PROJECT_CONF="project_dev"

  seta-ui:
    env_file:
      - .env.dev
    build: 
       context: ../seta-ui
       dockerfile: Dockerfile-dev-flask
    ports:
      - "5678:5678"
    volumes: 
      - ../seta-ui:/home/seta
      - seta-models3:/home/seta/models

  seta-ui-react:
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    build: 
       context: ../seta-react
       dockerfile: Dockerfile-dev
    volumes: 
      - ../seta-react:/home/seta
      - /home/seta/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true