FROM ubuntu:22.04

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
RUN echo "Acquire::https::Proxy \""$HTTPS_PROXY"\";" >> /etc/apt/apt.conf

ENV https_proxy=$HTTPS_PROXY
ENV http_proxy=$HTTP_PROXY

ENV HTTPS_PROXY=$HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY

RUN apt update -y 
RUN apt install -y  --no-install-recommends curl
RUN apt install -y  --no-install-recommends wget
RUN apt install -y  --no-install-recommends python3-pip
RUN pip install --upgrade pip

RUN useradd -m seta

ARG ROOT=/home/seta

#set UTC timezone
RUN apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/UTC /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

COPY ./seta-ui/requirements.txt $ROOT/requirements.txt

WORKDIR $ROOT
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./seta-ui/app_ui $ROOT/app_ui
COPY ./seta-ui/seta_flask_server $ROOT/seta_flask_server
COPY ./seta-ui/migrations $ROOT/migrations

#copy configuration files
COPY ./seta-config/ui.conf /etc/seta/
COPY ./seta-config/logs.conf /etc/seta/

CMD ["gunicorn", "--conf", "/home/seta/app_ui/gunicorn_conf.py", "--bind", "0.0.0.0:8080", "--capture-output" , "--access-logformat", "[seta.ui] %(h)s %(l)s %(u)s %(t)s %(r)s %(s)s %(b)s | %(f)s | %(a)s", "--chdir", "/home/seta/app_ui", "app:app"]
