version: "3.9"
services:
  seta-es:
    container_name: seta-es
    restart: always
    build: ./
    expose:
      - "9200"
      - "9300"
    mem_limit: "4g"
    volumes: 
      - seta-es:/usr/share/elasticsearch/data
    networks: 
      - seta-network
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120














networks:
  seta-network:
    name: seta-network
    driver: bridge

volumes:
  seta-es:
