version: "3.8"
services:
  seta-nginx:
    container_name: seta-nginx
    restart: always
    build: ./
    ports:
      - "80:80"
    depends_on:
      - "seta-api"
      - "seta-ui"
    networks: 
      - seta-network

networks:
  seta-network:
    name: seta-network
    driver: bridge

