FROM nginx:1.20.2

ENV https_proxy=$HTTP_PROXY
ENV http_proxy=$HTTP_PROXY
ENV no_proxy="seta-es-test,seta-mongo-test,seta-api-test,seta-nginx-test,seta-ui-test"

RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/

RUN rm /etc/nginx/conf.d/default.conf
COPY project_test.conf /etc/nginx/conf.d/default.conf
