FROM python:3.9.10-bullseye

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
ENV https_proxy=$HTTP_PROXY
ENV http_proxy=$HTTP_PROXY
ENV no_proxy="seta-es,seta-mongo,seta-api,seta-nginx,seta-ui,seta-ui-spa"

RUN apt update -y && apt-get install -y nodejs npm && useradd -m seta

ARG ROOT=/home/seta

# RUN npm install primereact
# RUN npm install primeicons
# RUN npm install axios
#RUN ng update -g

CMD chdir /home/seta/seta-frontend/ \
    && npm install primereact \
    && npm install primeicons \
    && npm install axios \
    && npm install \
    #&&  npm run build -c=docker --watch --build-optimizer=false --aot=false --optimization=false --output-path=/home/seta/seta-flask-server/seta-ui/ \
    && npm start --host '0.0.0.0' --port 3000 