api-host: seta-api
api-port: 8081
es-host: seta-es:9200
index: [seta-public-000001, seta-private-000001]
index-suggestion: seta-suggestion-000001
index_public: seta-public-000001
index_private: seta-private-000001
#index-wiki: seta-wiki-000002
models-path: /home/seta/models/
models-word2vec-file: wv-sg0-hs1.bin
models-word2vec-file-crc: wv-sg0-hs1.crc

env:
secret-key-path: key.txt
example-guest: example_get-token_guest.py
example-user: example_get-token_user.py
mongodb-host: mongodb://seta-mongo:27017/
jrcbox-id: RIDmCxbRmK2PBuK
jrcbox-path: https://jrcbox.jrc.ec.europa.eu/index.php/s/
jrcbox-pass: Op-next-seta-2022-14-14
jrcbox-webdav: https://jrcbox.jrc.ec.europa.eu/public.php/webdav/
#es-init-data-dump-file: dump10000.zip
#es-init-data-dump-file: seta-public-000001-data.json
es-init-data-dump-file: seta-public-000001-8.2-data.zip
es-update-data-dump-file: dump10000_up.zip
#es-init-data-config-file: mapping.json
#es-init-data-config-file: seta-public-000001-mapping.json
es-init-data-config-file: seta-public-000001-8.2-mapping.json
models-init-file: models.zip

user: username
pass: userpass
user8.2: username
pass8.2: userpass
#models-path-production: /home/seta/models_june_2021/
##models-path-dev: C:\Projects\models\
#models-path-dev: C:\Projects\models-june-2021\
#w2v-path: word2vec/wv-sg0hs1.bin
#w2v-crc-path: word2vec/wv-sg0hs1.crc

