FROM ubuntu:20.04

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
ENV https_proxy=$HTTP_PROXY
ENV http_proxy=$HTTP_PROXY
ENV no_proxy="seta-es,seta-mongo,seta-api,seta-nginx,seta-ui,seta-ui-spa"
ENV HTTPS_PROXY=$HTTP_PROXY
ENV HTTP_PROXY=$HTTP_PROXY
ENV NO_PROXY=$no_proxy

RUN apt update -y
RUN apt install -y  --no-install-recommends curl
RUN apt install -y  --no-install-recommends wget
RUN apt install -y  --no-install-recommends openjdk-11-jre
#RUN apt install -y  --no-install-recommends nodejs 
#RUN apt install -y  --no-install-recommends npm
RUN apt install -y  --no-install-recommends gnupg
RUN apt install -y  --no-install-recommends python3-pip
RUN apt install -y  --no-install-recommends python3-dev


ARG ROOT=/home/seta

#set UTC timezone
RUN apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/UTC /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN export  https_proxy=$HTTP_PROXY
RUN export  http_proxy=$HTTP_PROXY

RUN mkdir -p $ROOT/tika
WORKDIR $ROOT/tika
RUN wget https://archive.apache.org/dist/tika/2.4.1/tika-app-2.4.1.jar \
    && wget https://archive.apache.org/dist/tika/2.4.1/tika-app-2.4.1.jar.asc \
    && wget https://archive.apache.org/dist/tika/KEYS \
    && gpg --import KEYS \
    && gpg --verify tika-app-2.4.1.jar.asc tika-app-2.4.1.jar

WORKDIR $ROOT
COPY requirements.txt $ROOT/requirements.txt
RUN pip3 install -r $ROOT/requirements.txt 
RUN  python3 -m nltk.downloader punkt 
RUN python3 -c 'from sentence_transformers import SentenceTransformer; SentenceTransformer("all-distilroberta-v1")'

ENV FLASK_DEBUG=1
ENV FLASK_RUN_PORT=8081
ENV PYTHONUNBUFFERED=1
ENV FLASK_APP=app_dev.py 
ENV FLASK_ENV=development 

#CMD ["gunicorn", "--conf", "/home/seta/gunicorn_conf.py", "--reload", "--bind", "0.0.0.0:8081", "--capture-output" , "--access-logformat", "[seta.api] %(h)s %(l)s %(u)s %(t)s. %(r)s. %(s)s %(b)s. %(f)s. %(a)s", "--chdir", "/home/seta", "app_dev:app"]
CMD flask run --host 0.0.0.0
