FROM python:3.9.10-bullseye

RUN apt update -y
RUN apt install -y curl
RUN apt install -y openjdk-11-jre
#RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
RUN apt install -y nodejs 
RUN apt install -y npm 
RUN npm install elasticdump -g

ARG ROOT=/home/seta
WORKDIR $ROOT

RUN mkdir $ROOT/tika
WORKDIR $ROOT/tika
RUN wget https://dlcdn.apache.org/tika/2.4.1/tika-app-2.4.1.jar
RUN wget https://downloads.apache.org/tika/2.4.1/tika-app-2.4.1.jar.asc
RUN wget https://downloads.apache.org/tika/KEYS
RUN gpg --import KEYS
RUN gpg --verify tika-app-2.4.1.jar.asc tika-app-2.4.1.jar
WORKDIR $ROOT


COPY requirements.txt $ROOT/requirements.txt
RUN pip install -r $ROOT/requirements.txt

RUN python -m nltk.downloader punkt
RUN python -c 'from sentence_transformers import SentenceTransformer; SentenceTransformer("all-distilroberta-v1")'

ENV FLASK_ENV="development"
ENV FLASK_APP=main.py
ENV FLASK_RUN_PORT=8081
ENV FLASK_DEBUG=1
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

CMD flask run --host 0.0.0.0 --no-reload --with-threads