FROM python:3.9.10-bullseye

RUN apt update -y
RUN apt install -y curl
RUN apt install -y openjdk-11-jre
#RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
RUN apt install -y nodejs 
RUN apt install -y npm 
RUN npm install elasticdump -g
RUN useradd -M seta 

ARG ROOT=/home/seta
WORKDIR $ROOT

RUN chown -R seta /home/seta 

#USER seta

RUN mkdir $ROOT/tika
WORKDIR $ROOT/tika
RUN wget https://dlcdn.apache.org/tika/2.4.1/tika-app-2.4.1.jar
RUN wget https://downloads.apache.org/tika/2.4.1/tika-app-2.4.1.jar.asc
RUN wget https://downloads.apache.org/tika/KEYS
RUN gpg --import KEYS
RUN gpg --verify tika-app-2.4.1.jar.asc tika-app-2.4.1.jar
WORKDIR $ROOT


COPY requirements.txt $ROOT/requirements.txt
RUN pip install -r $ROOT/requirements.txt
RUN python -m nltk.downloader punkt
RUN python -c 'from sentence_transformers import SentenceTransformer; SentenceTransformer("all-distilroberta-v1")'

ADD . .

#COPY ./ ./

#CMD ["gunicorn", "--conf", "/home/seta/gunicorn_conf.py", "--bind", "0.0.0.0:8081", "--capture-output" , "--access-logformat", "[seta.api] %(h)s %(l)s %(u)s %(t)s. %(r)s. %(s)s %(b)s. %(f)s. %(a)s", "--chdir", "/home/seta", "main:app"]
CMD export FLASK_RUN_PORT=8081 &&  export FLASK_APP=main.py && export FLASK_ENV=development && chdir /home/seta && flask run -h 0.0.0.0
#CMD ls
#CMD ["flask", "run", "-h", "0.0.0.0"]
