FROM node:18-slim

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
RUN echo "Acquire::https::Proxy \""$HTTPS_PROXY"\";" >> /etc/apt/apt.conf

ENV https_proxy=$HTTPS_PROXY
ENV http_proxy=$HTTP_PROXY

ENV HTTPS_PROXY=$HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY

# Activate corepack to enable PNPM
RUN corepack enable

ARG ROOT=/home/seta

# Run as non-root user
USER node

# Set the working directory and change the owner
WORKDIR $ROOT
RUN chown -R node:node $ROOT

# Install dependencies
COPY --chown=node:node package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy source code
COPY --chown=node:node . .

# Run the development server
CMD pnpm start --host '0.0.0.0' --port 3000
