FROM ubuntu:22.04 as docs

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
RUN echo "Acquire::https::Proxy \""$HTTPS_PROXY"\";" >> /etc/apt/apt.conf

ENV https_proxy=$HTTPS_PROXY
ENV http_proxy=$HTTP_PROXY

ENV HTTPS_PROXY=$HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY

ARG ROOT=/home/seta

RUN apt update -y
RUN apt install -y  --no-install-recommends python3-pip
RUN pip install --upgrade pip

RUN useradd seta

COPY requirements.txt $ROOT/requirements.txt

WORKDIR $ROOT
RUN pip install -r requirements.txt

# Expose MkDocs development server port
EXPOSE 8000

# Start development server by default
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]