site_name: SeTA Docs
site_description: SeTA - Semantic Text Analyser
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
    logo: material/tree
    favicon: img/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: cyan
      accent: teal  
plugins:
  - search
  - render_swagger
markdown_extensions:
    - toc :
        permalink: true
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - md_in_html


nav:
  - Home: index.md
  - General Overview: 
    - Overview: general/overview.md
  - Apis:
    - Seta-api: seta-api/seta_api_v1.md
  - User-Guide: 
    - Tutorial: tutorial/tutorial.md
  - Deployment: 
    - Deployment Overview: deployment/deployment.md
  - FAQS: 
    - Help: faqs/faqs.md
  - Release: 
    - Release Notes: release-notes/release-notes.md
  - License: license/license_v1.md


