site_name: SeTA Documentation
site_description: SeTA - Semantic Text Analyser
theme:
  name: material
  custom_dir: overrides
  features:
    #- header.autohide
    - navigation.instant
    #- navigation.tabs
    - navigation.tracking
    - navigation.path
    #- navigation.expand
    - navigation.prune
    - toc.follow
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    admonition:
        note: octicons/note-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/flame-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
    logo: material/book-open-variant
    favicon: img/favicon.png
  palette:
    - scheme: seta
plugins:
  - search
  - render_swagger
  - markdownextradata
  - glightbox:
      zoomable: true
    
markdown_extensions:
    - toc :
        permalink: true
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - codehilite
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - footnotes
    - md_in_html
    - tables

extra:
  homepage: /docs
  setaUrls: 
    home: /
    apiCommunities: /seta-ui/api/v1/communities/doc
    apiSeta: /seta-api/doc
    jwtToken: /authentication/v1/doc
    docs: /docs
    login: /login
    auth_decode_Token: /authorization/v1/token_info
    auth_Token: /authorization/v1/doc
  setaNames:
    homeName: Seta WebApp
  seTALogo: material/home
  
extra_css:
  - stylesheets/extra.css
 
nav:
  - Introduction: index.md
  - Who should use it and why: general/who_use_it_and_why.md   
  - Using SeTA:
    - Configuration:
      - Web App: user-guide/configuration/webApp.md
      - Swagger: user-guide/configuration/swagger.md
      - APIs: user-guide/configuration/apis.md
    - Web App:
      - Communities: 
        - SeTA Communities: user-guide/communities/communities.md
      # - Communities ChangeRequest: user-guide/communitiesChangeRequest.md
        - Community Memberships: user-guide/communities/communityMemberships.md
        - Community Administrator: user-guide/communities/communityAdministrator.md
        - Resources: user-guide/communities/resources.md
      #  - Users Permissions: user-guide/usersPermissions.md
      - Search: 
        - Methodology: user-guide/search/methodology.md
        - Web Interface: user-guide/search/searchWebApp.md
    - APIs: 
      - JWT Token Authentication: apis/jwt_token/jwt_token_api.md
      - SeTA API: apis/seta_api/seta_api.md
      - SeTA Communities API: apis/seta_communities_api/seta_communities_api.md
  - Install SeTA:
    - Docker: setup/docker-architecture.md
    - MongoDB Migration: setup/db_migration.md
    - Deployment: setup/deployment.md 
    - Release: setup/release-notes.md
  - License: license/license_v1.md
  


