site_name: SeTA Docs
site_description: SeTA - Semantic Text Analyser
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    admonition:
        note: octicons/note-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/flame-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
    logo: material/note-search-outline
    favicon: img/favicon.png
  palette:
    - scheme: seta
plugins:
  - search
  - render_swagger
  - mike
    
markdown_extensions:
    - toc :
        permalink: true
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - codehilite
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - footnotes
    - md_in_html
    - tables
    
extra:
  version:
    provider: mike
  
extra_css:
  - stylesheets/extra.css
 
nav:
  - What is SeTA: 
      - What it does: index.md
      - Methodology: general/how-runs.md
      - Why you would use it: general/why-use-it.md
      - Who should/can use it: general/who-use-it.md      
  - Using SeTA:
    - Setup: user-guide/user-guide.md
    - Web Interface:
      - Search: user-guide/web-interface.md
      - Communities: user-guide/communities.md
    - API Interface:
      - Seta-api: seta-api/seta_api_v1.md
    - FAQS: 
      - FAQS: faqs/faqs.md
  - Deployment SeTA:
    - Deployment: deployment/deployment.md 
    - Advanced Tutorial: deployment/advanced-tutorial.md
    - Release: release-notes/release-notes.md
    - License: license/license_v1.md


