site_name: SeTA Documentation
site_description: SeTA - Semantic Text Analyser
# site_id for analytics
EU_Analytics_SiteID: b240c41b-yyyyy-40af-96ef-xxxxxxxx
has_cookies: true
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    admonition:
        note: octicons/note-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/flame-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
  favicon: img/SeTA-logo.png
  palette:
    - scheme: seta
plugins:
  - search
  - render_swagger
  - markdownextradata
  - glightbox:
      zoomable: true
    
markdown_extensions:
    - toc :
        permalink: true
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - codehilite
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - footnotes
    - md_in_html
    - tables

extra:
  homepage: /docs
  setaUrls:     
    home: /
    contact: /contact
    jwtToken: /authentication/v1
  setaNames:
    homeName: Seta WebApp
  
extra_css:
  - stylesheets/extra.css
 
nav:
  - Introduction: index.md
  - Who should use it and why: general/use-case.md   
  - SeTA User Guide:
    - Web App: 
      - About: user-guide/web-app.md
      - Data Sources: user-guide/data-sources.md
      - Search: 
        - Methodology: user-guide/search/methodology.md
        - Web Interface: user-guide/search/web-interface.md
      - User Profile:
        - Profile: user-guide/user-profile/profile.md
        - Authentication Key: user-guide/user-profile/authentication-key.md
        - Applications: user-guide/user-profile/applications.md
      - Administration Panel:
        - Users: user-guide/administration-panel/user-management.md
        - Annotations: user-guide/administration-panel/annotations.md
        - Data Sources: user-guide/administration-panel/data-sources.md
    - Web APIs: 
      - Concepts: apis/concepts.md
      - Access Token: apis/access-token.md
      - APIs: apis/api.md
  - Install SeTA:
    - Docker: setup/docker-architecture.md
    - Upgrade: setup/db-migration.md
    - Testing: setup/testing.md
  - License: license/license_v1.md