FROM ubuntu:22.04

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
RUN echo "Acquire::https::Proxy \""$HTTPS_PROXY"\";" >> /etc/apt/apt.conf

ENV https_proxy=$HTTPS_PROXY
ENV http_proxy=$HTTP_PROXY

ENV HTTPS_PROXY=$HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY

RUN apt update -y && apt install -y --no-install-recommends  nodejs npm
RUN apt install -y  --no-install-recommends curl

RUN npm update -g
RUN npm install -g n
RUN n lts
# Update npm to the latest version (fix EACCES error on node_modules/.cache in npm v>9)
RUN npm install -g npm

ARG ROOT=/home/seta

WORKDIR $ROOT

# Install dependencies
COPY package.json .
RUN npm install

# Copy source code
COPY . .

# Run the development server
CMD npm start -- --host '0.0.0.0' --port 3000