FROM ubuntu:22.04

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
RUN echo "Acquire::https::Proxy \""$HTTPS_PROXY"\";" >> /etc/apt/apt.conf

ENV https_proxy=$HTTPS_PROXY
ENV http_proxy=$HTTP_PROXY

ENV HTTPS_PROXY=$HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY

RUN apt update -y && apt install -y --no-install-recommends  nodejs npm
RUN apt install -y  --no-install-recommends curl

ARG ROOT=/home/seta

RUN npm update -g
RUN npm install -g n
RUN n lts
RUN npm install -g primereact
RUN npm install -g primeicons
RUN npm install -g axios
#update npm to the latest version (fix EACCES error on node_modules/.cache in npm v>9)
RUN npm install -g npm

WORKDIR $ROOT

ENV PATH $ROOT/node_modules/.bin:$PATH

ADD ./package.json $ROOT/package.json
ADD ./tsconfig.json $ROOT/tsconfig.json

RUN npm install

COPY ./src $ROOT/src
COPY ./public $ROOT/public

#RUN mkdir $ROOT/node_modules/.cache && chmod -R 777 $ROOT/node_modules/.cache

CMD chdir /home/seta/ \
    && npm start --host '0.0.0.0' --port 3000 
