#FROM python:3.9.10-bullseye
FROM ubuntu:22.04

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
ENV https_proxy=$HTTP_PROXY
ENV http_proxy=$HTTP_PROXY
ENV no_proxy="seta-es,seta-mongo,seta-api,seta-nginx,seta-ui,seta-ui-spa"

RUN apt update -y && apt install -y --no-install-recommends  nodejs npm
RUN apt install -y  --no-install-recommends curl

ARG ROOT=/home/seta

RUN npm update -g
RUN npm install -g n
RUN n lts
RUN npm install -g primereact
RUN npm install -g primeicons
RUN npm install -g axios

WORKDIR $ROOT

ENV PATH $ROOT/node_modules/.bin:$PATH

ADD ./package.json $ROOT/package.json
ADD ./tsconfig.json $ROOT/tsconfig.json

RUN npm install

COPY ./src $ROOT/src
COPY ./public $ROOT/public

CMD chdir /home/seta/ \
    && npm start --host '0.0.0.0' --port 3000 
