version: "3.8"
services:
  seta-mongo-test:
    container_name: seta-mongo-test
    restart: "no"
    build:
      context: ../seta-mongo
      dockerfile: Dockerfile-test
    ports:
      - "27018:27017"
    networks:
      - seta-network-test
    #volumes:
    #  - seta-mongo-test:/data/db

  seta-es-test:
    container_name: seta-es-test
    restart: "no"
    build:
      context: ../seta-es
      dockerfile: Dockerfile-test
    expose:
      - "9200"
      - "9300"
    mem_limit: "4g"
    volumes:
      - seta-es3-test:/usr/share/elasticsearch/data
    networks:
      - seta-network-test
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ingest.geoip.downloader.enabled=false

  seta-api-test:
    container_name: seta-api-test
    restart: "no"
    build:
      context: ../seta-api
      dockerfile: Dockerfile-test
    expose:
      - "8081"
    mem_limit: "8g"   
    networks:
      - seta-network-test
    depends_on:
      - "seta-mongo-test"
      - "seta-es-test"

  seta-nginx-test:
    container_name: seta-nginx-test
    restart: "no"
    build: 
       context: ../seta-nginx
       dockerfile: Dockerfile-test
    ports:
      - "8080:8080"
    depends_on:
      - "seta-api-test"
      - "seta-ui-test"
    networks:
      - seta-network-test

  seta-ui-test:
    container_name: seta-ui-test
    restart: "no"
    build: 
       context: ../seta-ui
       dockerfile: Dockerfile-test
    depends_on:
      - "seta-api-test"
    expose:
      - "8080"
    networks:
      - seta-network-test


  seta-data-test:
    container_name: seta-data-test
    build:
      context: ../seta-data
      dockerfile: Dockerfile-test
    depends_on:
      - "seta-es-test"
    volumes:
      - seta-models3-test:/home/seta/models
    networks:
      - seta-network-test


networks:
  seta-network-test:
    name: seta-network-test
    driver: bridge

volumes:
  #seta-mongo-test:
  seta-es3-test:
  seta-models3-test:
