FROM python:3.9.10-bullseye

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
ENV https_proxy=$HTTP_PROXY
ENV http_proxy=$HTTP_PROXY
ENV no_proxy="seta_es,seta-mongo,seta-api,seta-nginx,seta-ui,seta-ui-spa"

RUN apt update -y && useradd -m seta

ARG ROOT=/home/seta

RUN mkdir -p $ROOT/seta-frontend && mkdir -p $ROOT/seta-flask-server && mkdir -p $ROOT/models
COPY ./seta-flask-server/requirements.txt $ROOT/seta-flask-server/requirements.txt
WORKDIR $ROOT/seta-flask-server
RUN pip install -r requirements.txt

CMD chdir /home/seta/seta-flask-server \
    && export FLASK_RUN_PORT=8080 \
    && export FLASK_APP=app.py \
    && export FLASK_ENV=development \
    && python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run -h "0.0.0.0" 
