version: "3.9"
services:
  seta-ui:
    container_name: seta-ui
    restart: always
    build: ./
    depends_on:
      - "seta-api"
    expose:
      - "8080"
    networks: 
      - seta-network


networks:
  seta-network:
    name: seta-network
    driver: bridge
