FROM python:3.9.10-bullseye

RUN echo "Acquire::http::Proxy \""$HTTP_PROXY"\";" >> /etc/apt/apt.conf
ENV https_proxy=$HTTP_PROXY
ENV http_proxy=$HTTP_PROXY
ENV no_proxy="seta-es,seta-mongo,seta-api,seta-nginx,seta-ui,seta-ui-spa"

RUN apt update -y && useradd -m seta

ARG ROOT=/home/seta

RUN mkdir -p $ROOT/seta-flask-server && mkdir -p $ROOT/models
COPY ./seta-flask-server/requirements.txt $ROOT/seta-flask-server/requirements.txt
WORKDIR $ROOT/seta-flask-server
RUN pip install -r requirements.txt
RUN pip install ptvsd debugpy

ENV FLASK_ENV="development"
ENV FLASK_APP=app_dev.py
ENV FLASK_RUN_PORT=8080
ENV FLASK_DEBUG=1
ENV FLASK_PATH="http://localhost"
ENV API_TARGET_PATH="seta-api:8081/seta-api/api/v1"
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

CMD python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run -h "0.0.0.0" 
