version: "3.9"
services:
  seta-api:
    container_name: seta-api
    restart: always
    build: ./
    expose:
      - "8081"
    mem_limit: "8g"
    volumes: 
      - seta-models:/home/seta/models
    networks: 
      - seta-network
#    depends_on:
#      - "seta-mongo"
#      - "seta-es"

networks:
  seta-network:
    name: seta-network
    driver: bridge

volumes:
  seta-models:
